In [1]:
#library
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

C:\Users\91638\AppData\Local\Temp\ipykernel_9272\297894386.py:2: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
train_text=pd.read_csv("csv_files/train_with_embedding.csv")
dev_text=pd.read_csv("csv_files/dev_with_embedding.csv")
train_audio =pd.read_csv("csv_files/train_audio_df.csv")
dev_audio=pd.read_csv("csv_files/dev_audio_df.csv")

In [3]:
train_text

,Utterance,Emotion,file_name,text_embedded
0,also I was the point person on my companys tr...,neutral,dia0_utt0,[-1.31458908e-01 -1.72544960e-02 1.05243176e-...
1,You mustve had your hands full.,neutral,dia0_utt1,[-4.21393476e-02 4.15060222e-02 5.01765087e-...
2,That I did. That I did.,neutral,dia0_utt2,[ 5.02859987e-02 -5.54202916e-03 4.67068925e-...
3,So lets talk a little bit about your duties.,neutral,dia0_utt3,[ 3.89313884e-03 4.40940224e-02 5.99569939e-...
4,My duties? All right.,surprise,dia0_utt4,[-3.44950967e-02 1.93616357e-02 7.62079731e-...
...,...,...,...,...
9984,You or me?,neutral,dia1038_utt13,[-5.86172082e-02 7.39674866e-02 -8.01084377e-...
9985,"I got it. Uh, Joey, women don't have Adam's ap...",neutral,dia1038_utt14,[ 3.41740735e-02 3.57853919e-02 -2.12731548e-...
9986,"You guys are messing with me, right?",surprise,dia1038_utt15,[ 3.10330987e-02 8.54950678e-03 8.30181912e-...
9987,Yeah.,neutral,dia1038_utt16,[-1.46411374e-01 5.65296644e-03 -9.10743885e-...
9988,"That was a good one. For a second there, I was...",joy,dia1038_utt17,[-6.61767945e-02 4.18872088e-02 3.14832246e-...

In [4]:
train_audio

            filename                                     extracted_data
0      dia0_utt0.wav  [[ 1.34087457e-01  6.27370715e-01  4.40108806e...
1      dia0_utt1.wav  [[ 1.29256811e-01  6.26780272e-01  4.16521072e...
2     dia0_utt10.wav  [[ 1.25756048e-01  3.13562632e-01  2.48810440e...
3     dia0_utt11.wav  [[ 1.28282335e-01  4.98449355e-01  3.44894916e...
4     dia0_utt12.wav  [[ 2.17190213e-01  5.90898156e-01  5.22780955e...
...              ...                                                ...
9580   dia9_utt5.wav  [[ 1.00097656e-01  1.26352876e-01  6.21115081e...
9581   dia9_utt6.wav  [[ 9.71880351e-02  3.32032353e-01  2.18035161e...
9582   dia9_utt7.wav  [[ 9.63767723e-02  3.69627893e-01  3.85611951e...
9583   dia9_utt8.wav  [[ 1.18374023e-01  4.15460169e-01  3.70252579e...
9584   dia9_utt9.wav  [[ 9.51735805e-02  4.53799814e-01  4.89929855e...

[9585 rows x 2 columns]

In [5]:
dev_text

,Utterance,Emotion,file_name,text_embedded
0,"Oh my God, hes lost it. Hes totally lost it.",sadness,dia0_utt0,[ 7.69477896e-03 8.05744752e-02 3.29797901e-...
1,What?,surprise,dia0_utt1,[-1.01225428e-01 -1.85939856e-02 -4.19104882e-...
2,"Or! Or, we could go to the bank, close our acc...",neutral,dia1_utt0,[-6.23893365e-02 6.11942746e-02 -5.14132008e-...
3,Youre a genius!,joy,dia1_utt1,[ 4.66335472e-03 7.39181191e-02 3.60610485e-...
4,"Aww, man, now we wont be bank buddies!",sadness,dia1_utt2,[-1.47925746e-02 -3.13584022e-02 -1.89673230e-...
...,...,...,...,...
1104,No.,sadness,dia113_utt9,[-7.26952180e-02 1.45098493e-02 6.78025326e-...
1105,What? Oh my God! Im gonna miss you so much!,sadness,dia113_utt10,[ 2.34280918e-02 -2.82904729e-02 2.82736905e-...
1106,Im gonna miss you!,sadness,dia113_utt11,[-5.57095222e-02 -7.15075880e-02 6.42618388e-...
1107,I mean its the end of an era!,sadness,dia113_utt12,[ 2.98695527e-02 7.73971602e-02 5.36296740e-...
1108,I know!,sadness,dia113_utt13,[ 3.69448252e-02 5.69788925e-02 -2.08581183e-...

In [7]:
dev_audio

             filename                                     extracted_data
0       dia0_utt0.wav  [[ 1.19247437e-01  3.76063377e-01  3.39651704e...
1       dia0_utt1.wav  [[ 1.11476089e-01  3.62448841e-01  3.49401265e...
2     dia100_utt0.wav  [[ 1.33570772e-01  4.08948660e-01  4.17805076e...
3     dia101_utt0.wav  [[ 1.14804868e-01  3.85791451e-01  4.57476437e...
4     dia102_utt0.wav  [[ 1.17787679e-01  3.87339562e-01  3.59732747e...
...               ...                                                ...
1060    dia9_utt3.wav  [[ 8.63082321e-02  2.63172984e-01  2.61148840e...
1061    dia9_utt4.wav  [[ 2.51342773e-01  3.60552847e-01  4.15549904e...
1062    dia9_utt5.wav  [[ 8.53542752e-02  2.41658583e-01  2.97412246e...
1063    dia9_utt6.wav  [[ 1.02281359e-01  3.50548685e-01  4.14585352e...
1064    dia9_utt7.wav  [[ 8.30620660e-02  3.64871711e-01  4.04672354e...

[1065 rows x 2 columns]

In [8]:
train_text.columns

Index(['Utterance', 'Emotion', 'file_name', 'text_embedded'], dtype='object')

In [9]:
train_audio.columns

Index(['filename', 'extracted_data'], dtype='object')

In [10]:
train_audio['filename'] = train_audio['filename'].str.replace('.wav', '')

In [11]:
train_audio

        filename                                     extracted_data
0      dia0_utt0  [[ 1.34087457e-01  6.27370715e-01  4.40108806e...
1      dia0_utt1  [[ 1.29256811e-01  6.26780272e-01  4.16521072e...
2     dia0_utt10  [[ 1.25756048e-01  3.13562632e-01  2.48810440e...
3     dia0_utt11  [[ 1.28282335e-01  4.98449355e-01  3.44894916e...
4     dia0_utt12  [[ 2.17190213e-01  5.90898156e-01  5.22780955e...
...          ...                                                ...
9580   dia9_utt5  [[ 1.00097656e-01  1.26352876e-01  6.21115081e...
9581   dia9_utt6  [[ 9.71880351e-02  3.32032353e-01  2.18035161e...
9582   dia9_utt7  [[ 9.63767723e-02  3.69627893e-01  3.85611951e...
9583   dia9_utt8  [[ 1.18374023e-01  4.15460169e-01  3.70252579e...
9584   dia9_utt9  [[ 9.51735805e-02  4.53799814e-01  4.89929855e...

[9585 rows x 2 columns]

In [16]:
dev_audio['filename']=dev_audio['filename'].str.replace('.wav', '')

In [18]:
dev_audio

         filename                                     extracted_data
0       dia0_utt0  [[ 1.19247437e-01  3.76063377e-01  3.39651704e...
1       dia0_utt1  [[ 1.11476089e-01  3.62448841e-01  3.49401265e...
2     dia100_utt0  [[ 1.33570772e-01  4.08948660e-01  4.17805076e...
3     dia101_utt0  [[ 1.14804868e-01  3.85791451e-01  4.57476437e...
4     dia102_utt0  [[ 1.17787679e-01  3.87339562e-01  3.59732747e...
...           ...                                                ...
1060    dia9_utt3  [[ 8.63082321e-02  2.63172984e-01  2.61148840e...
1061    dia9_utt4  [[ 2.51342773e-01  3.60552847e-01  4.15549904e...
1062    dia9_utt5  [[ 8.53542752e-02  2.41658583e-01  2.97412246e...
1063    dia9_utt6  [[ 1.02281359e-01  3.50548685e-01  4.14585352e...
1064    dia9_utt7  [[ 8.30620660e-02  3.64871711e-01  4.04672354e...

[1065 rows x 2 columns]

In [19]:
train_merged = pd.merge(train_text, train_audio, left_on='file_name', right_on='filename', how='inner')

In [20]:
train_merged

,Utterance,Emotion,file_name,text_embedded,filename,extracted_data
0,also I was the point person on my companys tr...,neutral,dia0_utt0,[-1.31458908e-01 -1.72544960e-02 1.05243176e-...,dia0_utt0,[[ 1.34087457e-01 6.27370715e-01 4.40108806e...
1,You mustve had your hands full.,neutral,dia0_utt1,[-4.21393476e-02 4.15060222e-02 5.01765087e-...,dia0_utt1,[[ 1.29256811e-01 6.26780272e-01 4.16521072e...
2,That I did. That I did.,neutral,dia0_utt2,[ 5.02859987e-02 -5.54202916e-03 4.67068925e-...,dia0_utt2,[[ 1.41352635e-01 4.20076609e-01 5.89790702e...
3,So lets talk a little bit about your duties.,neutral,dia0_utt3,[ 3.89313884e-03 4.40940224e-02 5.99569939e-...,dia0_utt3,[[ 1.48058303e-01 3.64203542e-01 2.89357007e...
4,My duties? All right.,surprise,dia0_utt4,[-3.44950967e-02 1.93616357e-02 7.62079731e-...,dia0_utt4,[[ 1.30692093e-01 3.40013236e-01 3.58041942e...
...,...,...,...,...,...,...
9580,You or me?,neutral,dia1038_utt13,[-5.86172082e-02 7.39674866e-02 -8.01084377e-...,dia1038_utt13,[[ 7.92496928e-02 3.92701566e-01 3.90606403e...
9581,"I got it. Uh, Joey, women don't have Adam's ap...",neutral,dia1038_utt14,[ 3.41740735e-02 3.57853919e-02 -2.12731548e-...,dia1038_utt14,[[ 4.91480334e-02 3.59533757e-01 3.33861351e...
9582,"You guys are messing with me, right?",surprise,dia1038_utt15,[ 3.10330987e-02 8.54950678e-03 8.30181912e-...,dia1038_utt15,[[ 7.21214658e-02 3.30627710e-01 2.85190970e...
9583,Yeah.,neutral,dia1038_utt16,[-1.46411374e-01 5.65296644e-03 -9.10743885e-...,dia1038_utt16,[[ 1.05773926e-01 3.11412364e-01 2.20481411e...
9584,"That was a good one. For a second there, I was...",joy,dia1038_utt17,[-6.61767945e-02 4.18872088e-02 3.14832246e-...,dia1038_utt17,[[ 6.87934028e-02 2.44030550e-01 2.05981195e...

In [21]:
dev_merged = pd.merge(dev_text, dev_audio, left_on='file_name', right_on='filename', how='inner')

In [22]:
dev_merged

,Utterance,Emotion,file_name,text_embedded,filename,extracted_data
0,"Oh my God, hes lost it. Hes totally lost it.",sadness,dia0_utt0,[ 7.69477896e-03 8.05744752e-02 3.29797901e-...,dia0_utt0,[[ 1.19247437e-01 3.76063377e-01 3.39651704e...
1,What?,surprise,dia0_utt1,[-1.01225428e-01 -1.85939856e-02 -4.19104882e-...,dia0_utt1,[[ 1.11476089e-01 3.62448841e-01 3.49401265e...
2,"Or! Or, we could go to the bank, close our acc...",neutral,dia1_utt0,[-6.23893365e-02 6.11942746e-02 -5.14132008e-...,dia1_utt0,[[ 9.66525608e-02 3.44619930e-01 2.69980401e...
3,Youre a genius!,joy,dia1_utt1,[ 4.66335472e-03 7.39181191e-02 3.60610485e-...,dia1_utt1,[[ 1.98189113e-01 4.99972880e-01 4.97676671e...
4,"Aww, man, now we wont be bank buddies!",sadness,dia1_utt2,[-1.47925746e-02 -3.13584022e-02 -1.89673230e-...,dia1_utt2,[[ 1.11554181e-01 5.61635196e-01 4.66078222e...
...,...,...,...,...,...,...
1056,No.,sadness,dia113_utt9,[-7.26952180e-02 1.45098493e-02 6.78025326e-...,dia113_utt9,[[ 1.74738104e-01 3.38652074e-01 2.90151536e...
1057,What? Oh my God! Im gonna miss you so much!,sadness,dia113_utt10,[ 2.34280918e-02 -2.82904729e-02 2.82736905e-...,dia113_utt10,[[ 3.02812292e-01 3.65345895e-01 3.61546010e...
1058,Im gonna miss you!,sadness,dia113_utt11,[-5.57095222e-02 -7.15075880e-02 6.42618388e-...,dia113_utt11,[[ 2.00453272e-01 3.50698590e-01 2.96891421e...
1059,I mean its the end of an era!,sadness,dia113_utt12,[ 2.98695527e-02 7.73971602e-02 5.36296740e-...,dia113_utt12,[[ 2.13600852e-01 2.26801902e-01 3.21139663e...
1060,I know!,sadness,dia113_utt13,[ 3.69448252e-02 5.69788925e-02 -2.08581183e-...,dia113_utt13,[[ 1.21765137e-01 3.62470120e-01 2.80552119e...

In [23]:
train_merged.to_csv("train_merged.csv",index=False)
dev_merged.to_csv("dev_merged.csv",index=False)